# .github/workflows/doge.yml
name: Bot DOGE
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-doge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run DOGE Bot
        run: python main-doge.py
        env:
          SINGLE_CYCLE: 1
          OKX_API_KEY: ${{ secrets.OKX_API_KEY }}
          OKX_API_SECRET: ${{ secrets.OKX_API_SECRET }}
          OKX_PASSPHRASE: ${{ secrets.OKX_PASSPHRASE }}
          OKX_PASSWORD: ${{ secrets.OKX_PASSWORD }}
          OKX_SECRET_KEY: ${{ secrets.OKX_SECRET_KEY }}
