name: Senal v-LIVE

on:
  workflow_dispatch:
  schedule:
    - cron: '10 0,4,8,12,16,20 * * *'

jobs:
  senal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: pip install ccxt

      - name: Calcular señales
        run: python senal-hy.py
